#!/usr/bin/env bash
# $1 = The path to the file to be transferred
# $2 = The IP of the server we want to transfer the file to
# $3 = The username scp connects with
# $4 = The path to the SSH private key that scp uses

if [[ $# -ge 3 ]]
 then
	scp -i "$4" -o StrictHostKeyChecking=yes "$1" "$3"@"$2":~/;
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
fi

