#!/usr/bin/env bash
# $1 = The path to the file to be transferred
# $2 = The IP of the server we want to transfer the file to
# $3 = The username scp connects with
# $4 = The path to the SSH private key that scp uses

if [[ $# -eq 3 ]];
 then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
elif [[ $# -ge 4 ]];
 then
 	scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
fi

