#!/usr/bin/env bash
# installs nginx

sudo apt-get install -y nginx

sudo rm -f /var/www/html/index.nginx-debian.html

sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo nginx -s reload

