#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt update

sudo apt-get install -y nginx

ufw allow "Nginx HTTP"

sed -i "s|server_name\ _;|server_name _;\n\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;|" /etc/nginx/sites-available/default

echo "Hello World!" > /var/www/html/index.html

service nginx restart

