#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt update

sudo apt-get install -y nginx

ufw allow "Nginx HTTP"

sed -i "s|server_name\ _;|server_name _;\n\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;|" /etc/nginx/sites-available/default

Location="location = /404.html {\n\t\troot /var/www/html/;\n\t\tinternal;\n"
Error="error_page 404 /404.html;\n\t$Location"
FullError="}\n\n\t$Error\t}"

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i "0,/}/ s|}|$FullError|" /etc/nginx/sites-available/default

echo "Hello World!" > /var/www/html/index.html

service nginx restart

