#!/usr/bin/env bash
# fizzbuzz using bash

for i in {1..100};
do
	if [[ $((i % 3)) -ne 0 && $((i % 5)) -ne 0 ]]; then
		echo "$i"
		continue
	fi
	if [[ $((i % 3)) -eq 0 && $((i % 5)) -eq 0 ]]; then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]; then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]; then
		echo "Buzz"
	fi
done

