#!/usr/bin/env bash
# This script is displaying "Best School" 10 times except on the 9th it prints Hi after best School

i=1
while [ $i -le 10 ];
do
	((i++))
	echo "Best School"
	if [ $i == 10 ]; then
		echo "Hi"
	fi
done

