#!/usr/bin/env bash
# shows 12 hours

hour=0
minute=1

while [ $hour -ne 12 ];
do
	echo Hour: $hour
	echo $minute
	((minute++))
	if [ $minute -eq 60 ]; then
		minute=1
		((hour++))
	fi
done
echo echo Hour: $hour

